apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-dzff
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/happy-path-with-depl-tenant/appstudio/dc-metro-map-dzff@sha256:1e6d89bc124e55f406490b42438b450af9436891d998b1ecbf968fc8df748016
        name: my-nodejs
        resources: {}
status: {}
